name: proj1_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - nltk
  - ipykernel

# comments for me bc i will forget:
  # conda activate proj1_env
  # conda deactivate